 <?php 
/**
 * Template Name: users proj
 *
 */
get_header();?><?php

if(isset($_POST) && isset($_FILES)){
 //print_r($_POST); 
$my_post = array(
  'post_title'    => $_POST['title_name'],
  'post_content'  => $_POST['short_synopsis'],
  'post_status'   => 'publish',
  'post_author'   => $_POST['user'],
  'post_type'     => 'userproject',  
);
//echo $_POST['budget'];
// Insert the post into the database
$post_ID = wp_insert_post( $my_post ); 
update_post_meta( $post_ID, '_genre' , 'field_567cc09e82fca' );
update_post_meta( $post_ID, 'genre' , $_POST['genre'] );
update_post_meta( $post_ID, '_budget' , 'field_567cc05e82fc9' );
update_post_meta( $post_ID, 'budget' , $_POST['budget'] );
update_post_meta( $post_ID, '_production_stage' , 'field_567f437a24d21' );
update_post_meta( $post_ID, 'production_stage' , $_POST['production_stage'] );
update_post_meta( $post_ID, '_compares' , 'field_567cc0ce82fcb' );
update_post_meta( $post_ID, 'compares' , $_POST['compares'] );
update_post_meta( $post_ID, '_tax_breaks' , 'field_567cc0f482fcc' );
update_post_meta( $post_ID, 'tax_breaks' , $_POST['tax_breaks'] );
update_post_meta( $post_ID, '_cast' , 'field_567cc1a182fce' );
update_post_meta( $post_ID, 'cast' , $_POST['cast'] );
update_post_meta( $post_ID, '_team' , 'field_567cc16882fcd' );
update_post_meta( $post_ID, 'team' , $_POST['team'] );
update_post_meta( $post_ID, '_investor_info' , 'field_567cc1d282fcf' );
update_post_meta( $post_ID, 'investor_info' , $_POST['investor_info'] );
update_post_meta( $post_ID, '_target' , 'field_567cc23982fd0' );
update_post_meta( $post_ID, 'target' , $_POST['target'] );
update_post_meta( $post_ID, '_invested' , 'field_567cc27f82fd1' );
update_post_meta( $post_ID, 'invested' , $_POST['invested'] );
update_post_meta( $post_ID, '_soft' , 'field_567cc2de82fd2' );
update_post_meta( $post_ID, 'soft' , $_POST['soft'] );
update_post_meta( $post_ID, '_investers' , 'field_567cc30782fd3');
update_post_meta( $post_ID, 'investers' , $_POST['investers'] );

//echo $post_ID;

if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$uploadedfile = $_FILES['myfile'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && !isset( $movefile['error'] ) ) {
		$filename = $uploadedfile['name'];		
		$filetype = $uploadedfile['type'];
		$wp_upload_dir = wp_upload_dir();
		
		$attachment = array(
		'guid'           => $wp_upload_dir['url'] . '/' . basename( $filename ), 
		'post_mime_type' => $uploadedfile['type'],
		'post_title' => preg_replace('/\.[^.]+$/', '', $filename),
		'post_content' => '',
		'post_status' => 'inherit',
		'post_author' => $_POST['user'],
		'post_parent' => $post_ID
		);
		 $attach_id = wp_insert_attachment( $attachment, $filename);
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}
update_post_meta( $post_ID, '_thumbnail_id' , $attach_id );
wp_update_post( array(  'ID' => $post_ID ) );
//print_r($wp_upload_dir);
wp_redirect( 'http://themoviefund.com/newtheme/movie/' );
}
?>
<?php get_footer();?>